customCommands:
  - key: '<c-u>'
    context: 'commits'
    loadingText: "Pushing..."
    description: 'push up to commit'
    stream: yes
    command: 'git push {{if .CheckedOutBranch.IsTrackingRemote}}{{.CheckedOutBranch.UpstreamRemote}}{{else}}-u origin{{end}} {{.SelectedLocalCommit.Sha}}:{{if .CheckedOutBranch.IsTrackingRemote}}{{.CheckedOutBranch.UpstreamBranch}}{{else}}refs/heads/{{.CheckedOutBranch.Name}}{{end}}{{if .CheckedOutBranch.IsTrackingRemote}}{{else}} && git branch -u origin/{{.CheckedOutBranch.Name}}{{end}}'

