#!/usr/bin/env sh
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config										\
	layout						bsp					\
	window_placement			second_child		\
	top_padding					10					\
	bottom_padding				10					\
	left_padding				10					\
	right_padding				10					\
	window_gap					10					\
	auto_balance				off					\
	split_ratio					0.5					\
	mouse_follows_focus			on					\
	focus_follows_mouse			autoraise			\
	window_shadow				float				\
	window_opacity				on					\
	active_window_opacity		1.0					\
	normal_window_opacity		1.0					\
	external_bar				all:55:0

yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Karabiner Elements$" manage=off
yabai -m rule --add app="^Deezer$" manage=off
yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^Spark$" manage=off
yabai -m rule --add app="^Wally$" manage=off

# Notify sketchybar when spaces change
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=space_changed action="sketchybar --trigger space_change"
# Notify sketchybar when the focused app changes
yabai -m signal --add event=window_title_changed action="sketchybar --trigger title_change"

# janky borders
borders active_color=0xff89dceb inactive_color=0xff313244 width=7.0 style=round

echo "yabai configuration loaded.."

